name: Modify Package Version
on:
  push:
    branches:
      - 'release-**'

jobs:
 defaults:
    run:
      working-directory: ./exercises
  modify-version:
    runs-on: ubuntu-20.04
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          BRANCH_PREFIX: release-
