name: Modify Package Version
on:
  push:
    branches:
      - 'release-**'

jobs:
  modify-version:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./exercises
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          PACKAGE_DIR: exercises
          BRANCH_PREFIX: release-
          run: npx sort-package-json

  move-file:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    needs: modify-version
    steps:
    - name: check file
      run: |
        ls
    - name: move file
      run: mv -f package.json ./exercises/package.json

     
