name: Modify Package Version

on: push

jobs:
  modify-version:
    runs-on: ubuntu-20.04
    concurrency: ci-${{ github.ref }}
    env:
      working-directory: exercises
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
       # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          PACKAGE_DIR: exercises
          BRANCH_PREFIX: release-
